#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
#COPY ["app/EnglishSentence/EnglishSentence.csproj", "app/EnglishSentence/"]
#COPY ./*.sln  ./

COPY app/*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p app/${file%.*}/ && mv $file app/${file%.*}/ && dotnet restore app/${file%.*}/$file; done

#RUN dotnet restore

COPY ./app ./app
RUN ls -lrt
WORKDIR "/src/app/EnglishSentence"
RUN dotnet build "EnglishSentence.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "EnglishSentence.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "EnglishSentence.dll"]