version: '3.8'
services:
  app:
    build: 
        context: .
        dockerfile: ./EnglishSentence/Dockerfile
        
  app-test:
    build: 
        context: .
        dockerfile: ./EnglishSentence.Test/Dockerfile        
