steps:
  - label: ":testobject: Test"
    command: "find . -name '*.csproj' | xargs -n 1 dotnet test"
    plugins:
      - docker-compose#v4.7.0:
          run: app-test
          workdir: "/src/test"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}" 

  - wait

  - block: ":rocket: Push!"

  - label: ":docker: Push"
    plugins:
      - ecr#v2.7.0:
          login: true
          account_ids: "public.ecr.aws"
      - docker-compose#v4.7.0:
          push:
            - app:public.ecr.aws/k6a7e3i6/test-pipeline:${BUILDKITE_BUILD_NUMBER}
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

  - wait

  - block: ":rocket: Release!!"

  - trigger: "test-pipeline-deploy"
    build:
      message: "${BUILDKITE_MESSAGE}"
      commit: "${BUILDKITE_COMMIT}"
      branch: "${BUILDKITE_BRANCH}"  
        



