steps:
  - label: ":testobject: BuildTestImage"
    command: "dotnet test"
    plugins:
      - docker-compose#v4.7.0:
          build: app-test
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"  
      
  - wait

  - label: ":testobject: Test"
    command: "dotnet test"
    plugins:
      - docker-compose#v4.7.0:
          run: app-test
          workdir: "/src/test/EnglishSentence.Test"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

  - label: ":testobject: CoreUnitTest"
    command: "dotnet test"
    plugins:
      - docker-compose#v4.7.0:
          run: app-test
          workdir: "/src/test/EnglishSentenceCore.UnitTest"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"  

  - wait

  - block: ":rocket: Push!"

  - label: ":docker: Push"
    plugins:
      - ecr#v2.7.0:
          login: true
          account_ids: "public.ecr.aws"
      - docker-compose#v4.7.0:
          push:
            - app:public.ecr.aws/k6a7e3i6/test-pipeline:${BUILDKITE_BUILD_NUMBER}
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"

  - wait

  - block: ":rocket: Release!"

  - label: ":codedeploy: Deploy"
    command: BUILDKITE_BUILD_NUMBER=$BUILDKITE_BUILD_NUMBER ./deployment/script/deploy.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"